### ISSUE TITLE
Setup as Readme and should be a Lab

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/creating-and-inserting-dom-nodes#15]
The lesson tells students to:
> Open this lesson's `index.html` file in your browser and open up the browser's console. In the console, enter

However, there is no `index.html` file provided as the lab doesn't clone down. As far as I can tell.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @itzsaga.

We have updated the materials so that this lesson registers as a code along believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
