### ISSUE TITLE
Finished light doesn't stay on

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/creating-and-inserting-dom-nodes#17]
I'm not sure what makes it turn off, but I've clicked the Finished Reading button at least 4 times, and it doesn't stay on for more than a couple hours

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @KatieLars.

I was unable to replicate this issue, but we have recently updated the materials so that learn.co registers this lesson as a code along and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
