### ISSUE TITLE
Lesson Needs to be Set as a Readme

### ISSUE THREAD

**Issue by Saturn226** [learn-co-curriculum/creating-and-inserting-dom-nodes#24]
Students are unable to complete this lesson. It is a readme but the platform is treating it as a lab. 
@sgharms

**Comment by maxwellbenton** [comment]
Hi @Saturn226, 

Thank you for this feedback. This lesson is designed to require changes to the file contents before registering completion in order to encourage students to practice the code they are reading about. We've updated the instructions to this lesson to provide further guidance on how to register completion in this lesson, which should resolve this issue. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience so we can improve our content for future students.

Thank you!
